nav_links:
  type: objects
  default:
    - display_name: Latest
      title: topics with recent posts
      url: /latest
    - display_name: Categories
      title: all topics grouped by category
      url: /categories
    - display_name: Top
      title: the most active topics in the last year, month, week or day
      url: /top
  schema:
    name: link
    identifier: display_name
    properties:
      display_name:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 100
      title:
        type: string
        validations:
          min_length: 1
          max_length: 1000
      url:
        type: string
        required: true
        validations:
          min_length: 1
          max_length: 2048
          url: true
Hide_dropdowns:
  default: false
  description:
    en: "Hide category and tag dropdowns"
Hide_default_links:
  default: false
  description:
    en: "Hide the default links on both mobile and desktop."
